<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net11.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\KnowledgeSystem.Embedding\KnowledgeSystem.Embedding.csproj" />
      <ProjectReference Include="..\KnowledgeSystem.EmdParser\KnowledgeSystem.EmdParser.csproj" />
      <ProjectReference Include="..\KnowledgeSystem.Lexical\KnowledgeSystem.Lexical.csproj" />
      <ProjectReference Include="..\KnowledgeSystem.Vector.Hnsw\KnowledgeSystem.Vector.Hnsw.csproj" />
      <ProjectReference Include="..\KnowledgeSystems.Extensions\KnowledgeSystems.Extensions.csproj" />
    </ItemGroup>

</Project>
