<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net11.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\KnowledgeSystem.Agents\KnowledgeSystem.Agents.csproj" />
      <ProjectReference Include="..\KnowledgeSystem.Ai\KnowledgeSystem.Ai.csproj" />
      <ProjectReference Include="..\KnowledgeSystem.Api\KnowledgeSystem.Api.csproj" />
    </ItemGroup>

    <Target Name="CopyToLibrariesFolder" AfterTargets="Build">
        <Copy SourceFiles="$(TargetDir)$(AssemblyName).dll" DestinationFolder="..\KnowledgeSystem\bin\$(Configuration)\$(TargetFramework)\libraries\" SkipUnchangedFiles="true" />
    </Target>
    
</Project>
