<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net11.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\KnowledgeSystem.Ai\KnowledgeSystem.Ai.csproj" />
      <ProjectReference Include="..\KnowledgeSystem.Api\KnowledgeSystem.Api.csproj" />
      <ProjectReference Include="..\KnowledgeSystem.PluginLoader\KnowledgeSystem.PluginLoader.csproj" />
      <ProjectReference Include="..\KnowledgeSystem.Plugins.Library\KnowledgeSystem.Plugins.Library.csproj" />
      <ProjectReference Include="..\KnowledgeSystem.Retrieval.InMemory\KnowledgeSystem.Retrieval.InMemory.csproj" />
      <ProjectReference Include="..\KnowledgeSystem.Retrieval.Persistent\KnowledgeSystem.Retrieval.Persistent.csproj" />
      <ProjectReference Include="..\KnowledgeSystem.Retrieval\KnowledgeSystem.Retrieval.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="11.0.0-preview.4.26230.115" />
      <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="11.0.0-preview.3.26207.106" />
      <PackageReference Include="NetCord.Services" Version="1.0.0-alpha.489" />
    </ItemGroup>

    <Target Name="CopyToPluginsFolder" AfterTargets="Build">
        <Copy SourceFiles="$(TargetDir)$(AssemblyName).dll" DestinationFolder="..\KnowledgeSystem\bin\$(Configuration)\$(TargetFramework)\plugins\" SkipUnchangedFiles="true" />
    </Target>
    
</Project>
