<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net11.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\KnowledgeSystem.PluginLoader\KnowledgeSystem.PluginLoader.csproj" />
      <ProjectReference Include="..\..\KnowledgeSystem.Plugins.Library\KnowledgeSystem.Plugins.Library.csproj" />
      <ProjectReference Include="..\KnowledgeSystem.Api\KnowledgeSystem.Api.csproj" />
      <ProjectReference Include="..\KnowledgeSystem.PluginLoader\KnowledgeSystem.PluginLoader.csproj" />
      <ProjectReference Include="..\KnowledgeSystem.Plugins.Library\KnowledgeSystem.Plugins.Library.csproj" />
    </ItemGroup>


    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="11.0.0-preview.4.26230.115" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="11.0.0-preview.7.26381.103" />
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="11.0.0-preview.3.26207.106" />
        <PackageReference Include="NetCord.Hosting.Services" Version="1.0.0-alpha.489" />
        <PackageReference Include="NetCord.Services" Version="1.0.0-alpha.489" />
        <PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
        <PackageReference Include="Serilog.Extensions.Logging" Version="10.0.0" />
    </ItemGroup>

</Project>
