<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net11.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="6.0.4"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1"/>
        <PackageReference Include="xunit" Version="2.9.3"/>
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\KnowledgeSystem.Agents\KnowledgeSystem.Agents.csproj" />
      <ProjectReference Include="..\KnowledgeSystem.Plugins.Wiki\KnowledgeSystem.Plugins.Wiki.csproj" />
      <ProjectReference Include="..\KnowledgeSystem.Retrieval.InMemory\KnowledgeSystem.Retrieval.InMemory.csproj" />
      <ProjectReference Include="..\KnowledgeSystem.Retrieval.Persistent\KnowledgeSystem.Retrieval.Persistent.csproj" />
      <ProjectReference Include="..\KnowledgeSystem.Retrieval\KnowledgeSystem.Retrieval.csproj" />
      <ProjectReference Include="..\KnowledgeSystem.Vector.Hnsw\KnowledgeSystem.Vector.Hnsw.csproj" />
      <ProjectReference Include="..\KnowledgeSystem\KnowledgeSystem.csproj" />
      <ProjectReference Include="..\KnowledgeSystem.EmdParser\KnowledgeSystem.EmdParser.csproj" />
      <ProjectReference Include="..\KnowledgeSystem.Events\KnowledgeSystem.Events.csproj" />
    </ItemGroup>

</Project>